name: Generate emu config (Windows)

on:
  push:
    branches: [ "ci_runner" ]
  # pull_request:
  #   branches: [ "ci_runner" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Checkout branch
      uses: actions/checkout@v4
    
    - name: Install dependencies
      shell: cmd
      working-directory: ${{ github.workspace }}/scripts
      run: recreate_venv_win.bat

    - name: Rebuild
      shell: cmd
      working-directory: ${{ github.workspace }}/scripts
      run: rebuild_win.bat

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: "generate_emu_config-win-${{ github.sha }}"
        path: 'scripts/bin/win/'
        if-no-files-found: 'error'
        compression-level: 9
    