name: Emu build (Linux)

on:
  push:
    branches: [ 
      "ci-build-emu-linux*",
      "ci-build-all"
    ]
    tags:        
      - release*
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:
    # allows manual trigger

permissions:
  contents: write

env:
  THIRD_PARTY_BASE_DIR: 'third-party'

  DEPS_CACHE_KEY: emu-deps-linux
  DEPS_CACHE_DIR: build-linux-deps
  
  PACKAGE_ROOT_PATH: "build-linux/package"
  
jobs:
  dependencies:
    runs-on: ubuntu-22.04

    steps:
    - name: Lookup cache for deps
      id: emu-deps-cache-step
      # !tag && !pull_request
      if: |
        !startsWith(github.ref, 'refs/tags/') &&
        ${{ github.event_name != 'pull_request' }}
      uses: actions/cache@v3
      with:
        key: ${{ env.DEPS_CACHE_KEY }}
        path: ${{ env.DEPS_CACHE_DIR }}
        lookup-only: true

    # we need the repo to build the deps since it has the build scripts
    - name: Checkout branch
      if: steps.emu-deps-cache-step.outputs.cache-hit != 'true'
      uses: actions/checkout@v4

    - name: Clone third-party deps (deps/linux)
      if: steps.emu-deps-cache-step.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        ref: 'third-party/deps/linux'
        path: "${{env.THIRD_PARTY_BASE_DIR}}/deps/linux"

    - name: Clone third-party deps (deps/common)
      if: steps.emu-deps-cache-step.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        ref: 'third-party/deps/common'
        path: "${{env.THIRD_PARTY_BASE_DIR}}/deps/common"

    - name: Build deps
      if: steps.emu-deps-cache-step.outputs.cache-hit != 'true'
      shell: bash
      run: sudo chmod 777 build_linux_deps.sh && sudo ./build_linux_deps.sh


  build:
    needs: [ dependencies ]
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4

### deps
    - name: Grab cache for deps
      # !tag && !pull_request
      if: |
        !startsWith(github.ref, 'refs/tags/') &&
        ${{ github.event_name != 'pull_request' }}
      uses: actions/cache@v3
      with:
        key: ${{ env.DEPS_CACHE_KEY }}
        path: ${{ env.DEPS_CACHE_DIR }}
        fail-on-cache-miss: true

    - name: Install required packages
      shell: bash
      run: sudo chmod 777 build_linux_deps.sh && sudo ./build_linux_deps.sh -packages_only

    - name: Clone third-party build helpers (build/linux)
      uses: actions/checkout@v4
      with:
        ref: 'third-party/build/linux'
        path: "${{env.THIRD_PARTY_BASE_DIR}}/build/linux"

### build + upload release
    - name: Build release mode
      continue-on-error: true
      shell: bash
      working-directory: ${{ github.workspace }}
      run:  "sudo chmod 777 build_linux.sh && ./build_linux.sh release"

    - name: Package build (release)
      if: success()
      shell: bash
      working-directory: ${{ github.workspace }}
      run: sudo chmod 77 package_linux.sh && sudo ./package_linux.sh release

    - name: Upload build pacakge (release)
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: "build-linux-release-${{ github.sha }}"
        path: "${{ env.PACKAGE_ROOT_PATH }}/release/"
        if-no-files-found: 'error'
        compression-level: 9
        retention-days: 1
    
### build + upload debug
    - name: Build debug mode
      continue-on-error: true
      shell: bash
      working-directory: ${{ github.workspace }}
      run:  "sudo chmod 777 build_linux.sh && ./build_linux.sh debug"

    - name: Package build (debug)
      if: success()
      shell: bash
      working-directory: ${{ github.workspace }}
      run: sudo chmod 77 package_linux.sh && sudo ./package_linux.sh debug

    - name: Upload build pacakge (debug)
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: "build-linux-debug-${{ github.sha }}"
        path: "${{ env.PACKAGE_ROOT_PATH }}/debug/"
        if-no-files-found: 'error'
        compression-level: 9
        retention-days: 1
    
    - name: Release
      if: success() && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: "${{ env.PACKAGE_ROOT_PATH }}/**/*"
    